codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: nearest
  range: "70...100"

  status:
    project: no
    patch: no
    changes: no

  ignore:
    - "vendor"

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default