
ignored = ["github.com/magefile/mage/mg","github.com/magefile/mage/sh"]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "^3.2.0"

[[constraint]]
  name = "github.com/gosimple/slug"
  version = "^1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "^1.5.2"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "github.com/goenning/letteravatar"

[[constraint]]
  version = "0.1.0"
  name = "github.com/goenning/vat"

[[constraint]]
  branch = "master"
  name = "github.com/julienschmidt/httprouter"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  version = "v1.16.11"
  name = "github.com/aws/aws-sdk-go"

[[constraint]]
  version = "v55.3.0"
  name = "github.com/stripe/stripe-go"

[[constraint]]
  version = "v1.5.0"
  name = "github.com/disintegration/imaging"

[[constraint]]
  branch = "master"
  name = "github.com/joeshaw/envdecode"

